### ISSUE TITLE
Error when running optimize

### ISSUE THREAD

**Issue by FranzHell** [jesse-ai/jesse#107]
Process Process-12:
Traceback (most recent call last):
  File "/home/luckyluke/anaconda3/envs/trading-bot/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/luckyluke/anaconda3/envs/trading-bot/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/luckyluke/trading-bot/jesse/jesse/modes/optimize_mode/Genetics.py", line 91, in get_fitness
    raise e
  File "/home/luckyluke/trading-bot/jesse/jesse/modes/optimize_mode/Genetics.py", line 85, in get_fitness
    fitness_score, fitness_log = self.fitness(dna)
  File "/home/luckyluke/trading-bot/jesse/jesse/modes/optimize_mode/__init__.py", line 94, in fitness
    simulator(self.training_candles, hp)
  File "/home/luckyluke/trading-bot/jesse/jesse/modes/backtest_mode/__init__.py", line 158, in simulator
    r.strategy = StrategyClass()
  File "/home/luckyluke/trading-bot/jesse/name-of-project2/strategies/FAsterForecastStrategy/__init__.py", line 48, in __init__
    candles = research.get_candles('Binance', 'XRPUSDT', '4h', '2018-05-05','2020-12-25')
  File "/home/luckyluke/trading-bot/jesse/jesse/research/get_candles.py", line 51, in get_candles
    candles = np.array(tuple(candles_tuple))
  File "/home/luckyluke/anaconda3/envs/trading-bot/lib/python3.8/site-packages/peewee.py", line 6850, in __iter__
    self.execute()
  File "/home/luckyluke/anaconda3/envs/trading-bot/lib/python3.8/site-packages/peewee.py", line 1898, in inner
    return method(self, database, *args, **kwargs)
  File "/home/luckyluke/anaconda3/envs/trading-bot/lib/python3.8/site-packages/peewee.py", line 1969, in execute
    return self._execute(database)
Process Process-5:
  File "/home/luckyluke/anaconda3/envs/trading-bot/lib/python3.8/site-packages/peewee.py", line 2141, in _execute
    cursor = database.execute(self)
  File "/home/luckyluke/anaconda3/envs/trading-bot/lib/python3.8/site-packages/peewee.py", line 3142, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/home/luckyluke/anaconda3/envs/trading-bot/lib/python3.8/site-packages/peewee.py", line 3136, in execute_sql
    self.commit()
  File "/home/luckyluke/anaconda3/envs/trading-bot/lib/python3.8/site-packages/peewee.py", line 2902, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/home/luckyluke/anaconda3/envs/trading-bot/lib/python3.8/site-packages/peewee.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/home/luckyluke/anaconda3/envs/trading-bot/lib/python3.8/site-packages/peewee.py", line 3129, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: SSL error: wrong version number

Traceback (most recent call last):
  File "/home/luckyluke/anaconda3/envs/trading-bot/lib/python3.8/site-packages/peewee.py", line 3129, in execute_sql
    cursor.execute(sql, params or ())
**psycopg2.OperationalError: SSL error: wrong version number**

Can u help?

**Comment by FranzHell** [comment]
get_candles  works fine normally, also during normal backtest
