### ISSUE TITLE
Redis Authentication

### ISSUE THREAD

**Issue by emansammuta100533** [jesse-ai/jesse#3]
In the config.py it is required to input redis server details but I'm trying to use redislabs.com which requires a password and adding a key 'redis_password' doesn't work.

Is there a way to go about this or a patch needs to fix this?

Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\pydoc.py", line 346, in safeimport
    module = __import__(path)
  File "D:\MEGA\algorithm_development\jesse-binance-trader\config.py", line 20
loading candles...
EXCEPTION TRACEBACK:
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\jesse.exe\__main__.py", line 7, in <module>
    sys.exit(cli())
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\jesse\__init__.py", line 286, in backtest
    backtest_mode.run(start_date, finish_date, chart=chart, tradingview=tradingview)
  File "c:\programdata\anaconda3\lib\site-packages\jesse\modes\backtest_mode\__init__.py", line 40, in run
    candles = _load_candles(start_date, finish_date)
  File "c:\programdata\anaconda3\lib\site-packages\jesse\modes\backtest_mode\__init__.py", line 91, in _load_candles
    required_candles.load_required_candles(c[0], c[1], start_date_str, finish_date_str),
  File "c:\programdata\anaconda3\lib\site-packages\jesse\services\required_candles.py", line 40, in load_required_candles
    cached_value = cache.get_cache(cache_key)
  File "c:\programdata\anaconda3\lib\site-packages\jesse\services\cache.py", line 21, in get_cache
    exists = self.db.exists(key)
  File "c:\programdata\anaconda3\lib\site-packages\redis\client.py", line 1307, in exists
    return self.execute_command('EXISTS', *names)
  File "c:\programdata\anaconda3\lib\site-packages\redis\client.py", line 839, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "c:\programdata\anaconda3\lib\site-packages\redis\client.py", line 853, in parse_response
    response = connection.read_response()
  File "c:\programdata\anaconda3\lib\site-packages\redis\connection.py", line 687, in read_response
    response = self._parser.read_response()
  File "c:\programdata\anaconda3\lib\site-packages\redis\connection.py", line 315, in read_response
    raise error

 Uncaught Exception: AuthenticationError: Authentication required

**Comment by saleh-mir** [comment]
I should have set a config value for it. I'll push a new update for in a few minutes

**Comment by emansammuta100533** [comment]
> I should have set a config value for it. I'll push a new update for in a few minutes

Thanks, Yeah in jesse/services/cache.py I added the following line : 
`password=config['env']['databases'].get('redis_password', 'password'),`

And it worked, cool project by the way!

**Comment by saleh-mir** [comment]
> And it worked

Are you sure? I just pushed the update seconds ago. Thanks 

> cool project by the way!
Thanks!

**Comment by saleh-mir** [comment]
Oh you added it to the `cache.py`. Yes that is the fix.
