### ISSUE TITLE
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

### ISSUE THREAD

**Issue by mahiso** [jesse-ai/jesse#304]
Exception during backtest: ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

Docker build based on commit d9f383cb74b2d979a0e991f59f5d698d3796caa4
Docker Host: Debian 11 / Docker version 20.10.5

Candles from 01.01.2021 to now
Backtest:
  - Route: Binance / BTC-USDT / 15m / ExampleStrategy
  - Duration 05.01.2021 to 01.06.2021
 
Exeception:
```
Traceback (most recent call last):
jesse       |   File "/usr/local/lib/python3.9/pydoc.py", line 435, in safeimport
jesse       |     module = __import__(path)
jesse       |   File "/home/strategies/MyStrategy01/__init__.py", line 2, in <module>
jesse       |     import jesse.indicators as ta
jesse       |   File "/jesse-docker/jesse/indicators/__init__.py", line 1, in <module>
jesse       |     from .acosc import acosc
jesse       |   File "/jesse-docker/jesse/indicators/acosc.py", line 4, in <module>
jesse       |     import talib
jesse       |   File "/usr/local/lib/python3.9/site-packages/talib/__init__.py", line 93, in <module>
jesse       |     from ._ta_lib import (
jesse       |   File "talib/_ta_lib.pyx", line 1, in init talib._ta_lib
jesse       | ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
jesse       | 
jesse       | During handling of the above exception, another exception occurred:
jesse       | 
jesse       | Traceback (most recent call last):
jesse       |   File "/jesse-docker/jesse/services/multiprocessing.py", line 19, in run
jesse       |     mp.Process.run(self)
jesse       |   File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
jesse       |     self._target(*self._args, **self._kwargs)
jesse       |   File "/jesse-docker/jesse/modes/backtest_mode.py", line 104, in run
jesse       |     simulator(candles, run_silently=jh.should_execute_silently())
jesse       |   File "/jesse-docker/jesse/modes/backtest_mode.py", line 239, in simulator
jesse       |     StrategyClass = jh.get_strategy_class(r.strategy_name)
jesse       |   File "/jesse-docker/jesse/helpers.py", line 292, in get_strategy_class
jesse       |     return locate(f'strategies.{strategy_name}.{strategy_name}')
jesse       |   File "/usr/local/lib/python3.9/pydoc.py", line 1714, in locate
jesse       |     nextmodule = safeimport('.'.join(parts[:n+1]), forceload)
jesse       |   File "/usr/local/lib/python3.9/pydoc.py", line 450, in safeimport
jesse       |     raise ErrorDuringImport(path, sys.exc_info())
jesse       | pydoc.ErrorDuringImport: problem in strategies.MyStrategy01 - ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

Same exception during test run:
```
docker build -f DockerfileTest -t jesse-test .
docker run jesse-test
````
Test Output:
```
============================= test session starts ==============================
platform linux -- Python 3.9.9, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /jesse-docker
plugins: cov-3.0.0
collected 218 items / 1 error / 217 selected

==================================== ERRORS ====================================
__________________ ERROR collecting tests/test_indicators.py ___________________
tests/test_indicators.py:3: in <module>
    import jesse.indicators as ta
jesse/indicators/__init__.py:1: in <module>
    from .acosc import acosc
jesse/indicators/acosc.py:4: in <module>
    import talib
/usr/local/lib/python3.9/site-packages/talib/__init__.py:93: in <module>
    from ._ta_lib import (
talib/_ta_lib.pyx:1: in init talib._ta_lib
    ???
E   ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

----------- coverage: platform linux, python 3.9.9-final-0 -----------
Name                                                                                                       Stmts   Miss  Cover
------------------------------------------------------------------------------------------------------------------------------
jesse/__init__.py                                                                                            244    170    30%
jesse/config.py                                                                                               18     13    28%
jesse/enums/__init__.py                                                                                       58      0   100%
jesse/exceptions/__init__.py                                                                                  38      0   100%
jesse/exchanges/__init__.py                                                                                    1      1     0%
jesse/exchanges/exchange.py                                                                                   25     25     0%
jesse/exchanges/sandbox/Sandbox.py                                                                            37     37     0%
jesse/exchanges/sandbox/__init__.py                                                                            1      1     0%
jesse/factories/__init__.py                                                                                    4      0   100%
jesse/factories/candle_factory.py                                                                             49     36    27%
jesse/factories/order_factory.py                                                                              18     12    33%
jesse/helpers.py                                                                                             521    400    23%
jesse/indicators/__init__.py                                                                                 176    175     1%
jesse/indicators/acosc.py                                                                                     14     11    21%
jesse/indicators/ad.py                                                                                         8      8     0%
jesse/indicators/adosc.py                                                                                      8      8     0%
jesse/indicators/adx.py                                                                                        8      8     0%
jesse/indicators/adxr.py                                                                                       8      8     0%
jesse/indicators/alligator.py                                                                                 22     22     0%
jesse/indicators/alma.py                                                                                      26     26     0%
jesse/indicators/ao.py                                                                                        13     13     0%
jesse/indicators/apo.py                                                                                        9      9     0%
jesse/indicators/aroon.py                                                                                     11     11     0%
jesse/indicators/aroonosc.py                                                                                   8      8     0%
jesse/indicators/atr.py                                                                                        8      8     0%
jesse/indicators/avgprice.py                                                                                   8      8     0%
jesse/indicators/bandpass.py                                                                                  36     36     0%
jesse/indicators/beta.py                                                                                       8      8     0%
jesse/indicators/bollinger_bands.py                                                                           23     23     0%
jesse/indicators/bollinger_bands_width.py                                                                     22     22     0%
jesse/indicators/bop.py                                                                                        8      8     0%
jesse/indicators/cc.py                                                                                         9      9     0%
jesse/indicators/cci.py                                                                                        8      8     0%
jesse/indicators/cfo.py                                                                                       13     13     0%
jesse/indicators/cg.py                                                                                        27     27     0%
jesse/indicators/chande.py                                                                                    29     29     0%
jesse/indicators/chop.py                                                                                      14     14     0%
jesse/indicators/cksp.py                                                                                      18     18     0%
jesse/indicators/cmo.py                                                                                       10     10     0%
jesse/indicators/correl.py                                                                                     8      8     0%
jesse/indicators/correlation_cycle.py                                                                         63     63     0%
jesse/indicators/cvi.py                                                                                        8      8     0%
jesse/indicators/cwma.py                                                                                      26     26     0%
jesse/indicators/damiani_volatmeter.py                                                                        30     30     0%
jesse/indicators/dec_osc.py                                                                                   12     12     0%
jesse/indicators/decycler.py                                                                                  10     10     0%
jesse/indicators/dema.py                                                                                      11     11     0%
jesse/indicators/devstop.py                                                                                   21     21     0%
jesse/indicators/di.py                                                                                        12     12     0%
jesse/indicators/dm.py                                                                                        12     12     0%
jesse/indicators/donchian.py                                                                                  13     13     0%
jesse/indicators/dpo.py                                                                                        9      9     0%
jesse/indicators/dti.py                                                                                       23     23     0%
jesse/indicators/dx.py                                                                                         8      8     0%
jesse/indicators/edcf.py                                                                                      28     28     0%
jesse/indicators/efi.py                                                                                       21     21     0%
jesse/indicators/ema.py                                                                                       11     11     0%
jesse/indicators/emd.py                                                                                       44     44     0%
jesse/indicators/emv.py                                                                                        8      8     0%
jesse/indicators/epma.py                                                                                      26     26     0%
jesse/indicators/er.py                                                                                        13     13     0%
jesse/indicators/eri.py                                                                                       14     14     0%
jesse/indicators/fisher.py                                                                                    11     11     0%
jesse/indicators/fosc.py                                                                                       9      9     0%
jesse/indicators/frama.py                                                                                     51     51     0%
jesse/indicators/fwma.py                                                                                      26     26     0%
jesse/indicators/gatorosc.py                                                                                  28     28     0%
jesse/indicators/gauss.py                                                                                     45     45     0%
jesse/indicators/high_pass.py                                                                                 24     24     0%
jesse/indicators/high_pass_2_pole.py                                                                          23     23     0%
jesse/indicators/hma.py                                                                                       11     11     0%
jesse/indicators/ht_dcperiod.py                                                                               10     10     0%
jesse/indicators/ht_dcphase.py                                                                                10     10     0%
jesse/indicators/ht_phasor.py                                                                                 13     13     0%
jesse/indicators/ht_sine.py                                                                                   13     13     0%
jesse/indicators/ht_trendline.py                                                                              12     12     0%
jesse/indicators/ht_trendmode.py                                                                              10     10     0%
jesse/indicators/hurst_exponent.py                                                                            62     62     0%
jesse/indicators/hwma.py                                                                                      30     30     0%
jesse/indicators/ichimoku_cloud.py                                                                            32     32     0%
jesse/indicators/ichimoku_cloud_seq.py                                                                        24     24     0%
jesse/indicators/ift_rsi.py                                                                                   11     11     0%
jesse/indicators/itrend.py                                                                                    27     27     0%
jesse/indicators/jma.py                                                                                       29     29     0%
jesse/indicators/jsa.py                                                                                       10     10     0%
jesse/indicators/kama.py                                                                                      12     12     0%
jesse/indicators/kaufmanstop.py                                                                               11     11     0%
jesse/indicators/kdj.py                                                                                       20     20     0%
jesse/indicators/keltner.py                                                                                   18     18     0%
jesse/indicators/kst.py                                                                                       18     18     0%
jesse/indicators/kurtosis.py                                                                                  12     12     0%
jesse/indicators/kvo.py                                                                                        8      8     0%
jesse/indicators/linearreg.py                                                                                 12     12     0%
jesse/indicators/linearreg_angle.py                                                                           12     12     0%
jesse/indicators/linearreg_intercept.py                                                                       12     12     0%
jesse/indicators/linearreg_slope.py                                                                           12     12     0%
jesse/indicators/lrsi.py                                                                                      41     41     0%
jesse/indicators/ma.py                                                                                       112    112     0%
jesse/indicators/maaq.py                                                                                      31     31     0%
jesse/indicators/mab.py                                                                                       19     19     0%
jesse/indicators/macd.py                                                                                      13     13     0%
jesse/indicators/macdext.py                                                                                   23     23     0%
jesse/indicators/mama.py                                                                                      15     15     0%
jesse/indicators/marketfi.py                                                                                   9      9     0%
jesse/indicators/mass.py                                                                                       8      8     0%
jesse/indicators/mcginley_dynamic.py                                                                          22     22     0%
jesse/indicators/mean_ad.py                                                                                   15     15     0%
jesse/indicators/median_ad.py                                                                                 14     14     0%
jesse/indicators/medprice.py                                                                                   8      8     0%
jesse/indicators/mfi.py                                                                                        8      8     0%
jesse/indicators/midpoint.py                                                                                  10     10     0%
jesse/indicators/midprice.py                                                                                   8      8     0%
jesse/indicators/minmax.py                                                                                    20     20     0%
jesse/indicators/mom.py                                                                                       10     10     0%
jesse/indicators/msw.py                                                                                       14     14     0%
jesse/indicators/mwdx.py                                                                                      22     22     0%
jesse/indicators/natr.py                                                                                       8      8     0%
jesse/indicators/nma.py                                                                                       28     28     0%
jesse/indicators/nvi.py                                                                                       10     10     0%
jesse/indicators/obv.py                                                                                        8      8     0%
jesse/indicators/pattern_recognition.py                                                                      130    130     0%
jesse/indicators/pfe.py                                                                                       14     14     0%
jesse/indicators/pivot.py                                                                                     60     60     0%
jesse/indicators/pma.py                                                                                       28     28     0%
jesse/indicators/ppo.py                                                                                       12     12     0%
jesse/indicators/pvi.py                                                                                       10     10     0%
jesse/indicators/pwma.py                                                                                      29     29     0%
jesse/indicators/qstick.py                                                                                     8      8     0%
jesse/indicators/reflex.py                                                                                    35     35     0%
jesse/indicators/rma.py                                                                                       38     38     0%
jesse/indicators/roc.py                                                                                       10     10     0%
jesse/indicators/rocp.py                                                                                      10     10     0%
jesse/indicators/rocr100.py                                                                                   10     10     0%
jesse/indicators/rocr.py                                                                                      10     10     0%
jesse/indicators/roofing.py                                                                                   11     11     0%
jesse/indicators/rsi.py                                                                                       10     10     0%
jesse/indicators/rsmk.py                                                                                      19     19     0%
jesse/indicators/rsx.py                                                                                       76     76     0%
jesse/indicators/rvi.py                                                                                       25     25     0%
jesse/indicators/safezonestop.py                                                                              15     15     0%
jesse/indicators/sar.py                                                                                        8      8     0%
jesse/indicators/sarext.py                                                                                     8      8     0%
jesse/indicators/sinwma.py                                                                                    14     14     0%
jesse/indicators/skew.py                                                                                      12     12     0%
jesse/indicators/sma.py                                                                                       12     12     0%
jesse/indicators/smma.py                                                                                      19     19     0%
jesse/indicators/sqwma.py                                                                                     26     26     0%
jesse/indicators/srsi.py                                                                                      17     17     0%
jesse/indicators/srwma.py                                                                                     26     26     0%
jesse/indicators/stc.py                                                                                       15     15     0%
jesse/indicators/stddev.py                                                                                    10     10     0%
jesse/indicators/stochastic.py                                                                                19     19     0%
jesse/indicators/stochf.py                                                                                    18     18     0%
jesse/indicators/supersmoother.py                                                                             22     22     0%
jesse/indicators/supersmoother_3_pole.py                                                                      23     23     0%
jesse/indicators/supertrend.py                                                                                58     58     0%
jesse/indicators/swma.py                                                                                      29     29     0%
jesse/indicators/t3.py                                                                                        12     12     0%
jesse/indicators/tema.py                                                                                      12     12     0%
jesse/indicators/trange.py                                                                                     8      8     0%
jesse/indicators/trendflex.py                                                                                 34     34     0%
jesse/indicators/trima.py                                                                                     12     12     0%
jesse/indicators/trix.py                                                                                      10     10     0%
jesse/indicators/tsf.py                                                                                       10     10     0%
jesse/indicators/tsi.py                                                                                       10     10     0%
jesse/indicators/ttm_trend.py                                                                                 11     11     0%
jesse/indicators/typprice.py                                                                                   8      8     0%
jesse/indicators/ui.py                                                                                        14     14     0%
jesse/indicators/ultosc.py                                                                                     8      8     0%
jesse/indicators/var.py                                                                                       10     10     0%
jesse/indicators/vi.py                                                                                        45     45     0%
jesse/indicators/vidya.py                                                                                     12     12     0%
jesse/indicators/vlma.py                                                                                      40     40     0%
jesse/indicators/vosc.py                                                                                       8      8     0%
jesse/indicators/voss.py                                                                                      34     34     0%
jesse/indicators/vpci.py                                                                                      17     17     0%
jesse/indicators/vpt.py                                                                                        9      9     0%
jesse/indicators/vpwma.py                                                                                     26     26     0%
jesse/indicators/vwap.py                                                                                      17     17     0%
jesse/indicators/vwma.py                                                                                      12     12     0%
jesse/indicators/vwmacd.py                                                                                    15     15     0%
jesse/indicators/wad.py                                                                                        8      8     0%
jesse/indicators/wclprice.py                                                                                   8      8     0%
jesse/indicators/wilders.py                                                                                   12     12     0%
jesse/indicators/willr.py                                                                                      8      8     0%
jesse/indicators/wma.py                                                                                       10     10     0%
jesse/indicators/wt.py                                                                                        21     21     0%
jesse/indicators/zlema.py                                                                                     12     12     0%
jesse/indicators/zscore.py                                                                                    20     20     0%
jesse/libs/__init__.py                                                                                         1      0   100%
jesse/libs/custom_json/__init__.py                                                                            11      7    36%
jesse/libs/dynamic_numpy_array/__init__.py                                                                    56     44    21%
jesse/models/Candle.py                                                                                        27      6    78%
jesse/models/CompletedTrade.py                                                                                65     18    72%
jesse/models/DailyBalance.py                                                                                  23     23     0%
jesse/models/Exchange.py                                                                                      40     15    62%
jesse/models/FuturesExchange.py                                                                              105     83    21%
jesse/models/Log.py                                                                                           21      6    71%
jesse/models/Option.py                                                                                        20     20     0%
jesse/models/Order.py                                                                                        134     76    43%
jesse/models/Orderbook.py                                                                                     17     17     0%
jesse/models/Position.py                                                                                     213    160    25%
jesse/models/Route.py                                                                                         10      8    20%
jesse/models/SpotExchange.py                                                                                  91     74    19%
jesse/models/Ticker.py                                                                                        20      5    75%
jesse/models/Trade.py                                                                                         21      5    76%
jesse/models/__init__.py                                                                                      11      0   100%
jesse/models/utils.py                                                                                         64     51    20%
jesse/modes/__init__.py                                                                                        0      0   100%
jesse/modes/backtest_mode.py                                                                                 235    199    15%
jesse/modes/data_provider.py                                                                                  99     99     0%
jesse/modes/import_candles_mode/__init__.py                                                                  155    131    15%
jesse/modes/import_candles_mode/drivers/__init__.py                                                            2      0   100%
jesse/modes/import_candles_mode/drivers/binance.py                                                            32     32     0%
jesse/modes/import_candles_mode/drivers/binance_futures.py                                                    36     36     0%
jesse/modes/import_candles_mode/drivers/binance_inverse_futures.py                                            38     27    29%
jesse/modes/import_candles_mode/drivers/bitfinex.py                                                           31     31     0%
jesse/modes/import_candles_mode/drivers/bybit_perpetual.py                                                    34     34     0%
jesse/modes/import_candles_mode/drivers/coinbase.py                                                           32     32     0%
jesse/modes/import_candles_mode/drivers/ftx_futures.py                                                        31     31     0%
jesse/modes/import_candles_mode/drivers/interface.py                                                          21     12    43%
jesse/modes/import_candles_mode/drivers/testnet_binance_futures.py                                            36     36     0%
jesse/modes/import_candles_mode/drivers/testnet_bybit_perpetual.py                                            34     34     0%
jesse/modes/optimize_mode/Optimize.py                                                                        173    173     0%
jesse/modes/optimize_mode/__init__.py                                                                         42     42     0%
jesse/modes/optimize_mode/fitness.py                                                                          86     86     0%
jesse/modes/utils.py                                                                                          18     13    28%
jesse/research/__init__.py                                                                                     3      0   100%
jesse/research/backtest.py                                                                                    38     33    13%
jesse/research/get_candles.py                                                                                 30     28     7%
jesse/research/store_candles.py                                                                                8      6    25%
jesse/routes/__init__.py                                                                                      52     31    40%
jesse/services/__init__.py                                                                                     0      0   100%
jesse/services/api.py                                                                                         56     56     0%
jesse/services/auth.py                                                                                        35     23    34%
jesse/services/broker.py                                                                                      62     44    29%
jesse/services/cache.py                                                                                       63     43    32%
jesse/services/candle.py                                                                                      56     46    18%
jesse/services/charts.py                                                                                      85     72    15%
jesse/services/db.py                                                                                          31     12    61%
jesse/services/env.py                                                                                         24     17    29%
jesse/services/failure.py                                                                                     21     14    33%
jesse/services/file.py                                                                                        35     26    26%
jesse/services/installer.py                                                                                   61     61     0%
jesse/services/jesse_trade.py                                                                                 36     36     0%
jesse/services/logger.py                                                                                      78     67    14%
jesse/services/metrics.py                                                                                     88     77    12%
jesse/services/migrator.py                                                                                    82     82     0%
jesse/services/multiprocessing.py                                                                             59     59     0%
jesse/services/notifier.py                                                                                    32     22    31%
jesse/services/progressbar.py                                                                                 41     26    37%
jesse/services/quantstats.py                                                                                  24     15    38%
jesse/services/redis.py                                                                                       32     17    47%
jesse/services/report.py                                                                                      83     61    27%
jesse/services/required_candles.py                                                                            53     42    21%
jesse/services/selectors.py                                                                                   30     20    33%
jesse/services/strategy_maker/ExampleStrategy/__init__.py                                                     14     14     0%
jesse/services/strategy_maker/__init__.py                                                                     16     16     0%
jesse/services/table.py                                                                                       15     15     0%
jesse/services/tradingview.py                                                                                 19     15    21%
jesse/services/validators.py                                                                                   4      2    50%
jesse/services/web.py                                                                                         79      0   100%
jesse/store/__init__.py                                                                                       82     52    37%
jesse/store/state_app.py                                                                                      13      2    85%
jesse/store/state_candles.py                                                                                 189    156    17%
jesse/store/state_completed_trades.py                                                                          8      2    75%
jesse/store/state_exchanges.py                                                                                21     12    43%
jesse/store/state_logs.py                                                                                      4      0   100%
jesse/store/state_orderbook.py                                                                                83     63    24%
jesse/store/state_orders.py                                                                                   48     30    38%
jesse/store/state_positions.py                                                                                16      9    44%
jesse/store/state_tickers.py                                                                                  32     18    44%
jesse/store/state_trades.py                                                                                   40     24    40%
jesse/strategies/Strategy.py                                                                                 685    540    21%
jesse/strategies/Test01/__init__.py                                                                           17     17     0%
jesse/strategies/Test02/__init__.py                                                                           17     17     0%
jesse/strategies/Test03/__init__.py                                                                           20     20     0%
jesse/strategies/Test04/__init__.py                                                                           18     18     0%
jesse/strategies/Test05/__init__.py                                                                           22     22     0%
jesse/strategies/Test06/__init__.py                                                                           20     20     0%
jesse/strategies/Test07/__init__.py                                                                           25     25     0%
jesse/strategies/Test08/__init__.py                                                                           20     20     0%
jesse/strategies/Test09/__init__.py                                                                           14     14     0%
jesse/strategies/Test10/__init__.py                                                                           17     17     0%
jesse/strategies/Test11/__init__.py                                                                           17     17     0%
jesse/strategies/Test12/__init__.py                                                                           20     20     0%
jesse/strategies/Test13/__init__.py                                                                           20     20     0%
jesse/strategies/Test14/__init__.py                                                                           20     20     0%
jesse/strategies/Test15/__init__.py                                                                           16     16     0%
jesse/strategies/Test16/__init__.py                                                                           22     22     0%
jesse/strategies/Test17/__init__.py                                                                           20     20     0%
jesse/strategies/Test18/__init__.py                                                                           19     19     0%
jesse/strategies/Test19/__init__.py                                                                           12     12     0%
jesse/strategies/Test20/__init__.py                                                                           17     17     0%
jesse/strategies/Test21/__init__.py                                                                           15     15     0%
jesse/strategies/Test22/__init__.py                                                                           13     13     0%
jesse/strategies/Test23/__init__.py                                                                           15     15     0%
jesse/strategies/Test24/__init__.py                                                                           13     13     0%
jesse/strategies/Test25/__init__.py                                                                           15     15     0%
jesse/strategies/Test26/__init__.py                                                                           13     13     0%
jesse/strategies/Test27/__init__.py                                                                           15     15     0%
jesse/strategies/Test28/__init__.py                                                                           12     12     0%
jesse/strategies/Test29/__init__.py                                                                           25     25     0%
jesse/strategies/Test30/__init__.py                                                                           19     19     0%
jesse/strategies/Test31/__init__.py                                                                           17     17     0%
jesse/strategies/Test32/__init__.py                                                                           18     18     0%
jesse/strategies/Test33/__init__.py                                                                           13     13     0%
jesse/strategies/Test34/__init__.py                                                                           17     17     0%
jesse/strategies/Test35/__init__.py                                                                            0      0   100%
jesse/strategies/Test36/__init__.py                                                                           24     24     0%
jesse/strategies/Test37/__init__.py                                                                           28     28     0%
jesse/strategies/Test38/__init__.py                                                                           18     18     0%
jesse/strategies/Test39/__init__.py                                                                           18     18     0%
jesse/strategies/Test40/__init__.py                                                                           13     13     0%
jesse/strategies/Test41/__init__.py                                                                           19     19     0%
jesse/strategies/Test44/__init__.py                                                                           14     14     0%
jesse/strategies/Test45/__init__.py                                                                           18     18     0%
jesse/strategies/Test46/__init__.py                                                                           16     16     0%
jesse/strategies/Test47/__init__.py                                                                           22     22     0%
jesse/strategies/Test48/__init__.py                                                                           14     14     0%
jesse/strategies/TestAfterMethod/__init__.py                                                                  18     18     0%
jesse/strategies/TestBeforeMethod/__init__.py                                                                 21     21     0%
jesse/strategies/TestCanCancelEntryOrdersAfterOpenPositionLong1/__init__.py                                   34     34     0%
jesse/strategies/TestCanCancelEntryOrdersAfterOpenPositionLong2/__init__.py                                   34     34     0%
jesse/strategies/TestCanCancelEntryOrdersAfterOpenPositionShort1/__init__.py                                  34     34     0%
jesse/strategies/TestCanCancelEntryOrdersAfterOpenPositionShort2/__init__.py                                  34     34     0%
jesse/strategies/TestCompletedTradeAfterExitingTrade/__init__.py                                              36     36     0%
jesse/strategies/TestDefaultHyperparameters/__init__.py                                                       17     17     0%
jesse/strategies/TestDnaMethod/__init__.py                                                                    19     19     0%
jesse/strategies/TestEmptyStrategy/__init__.py                                                                12     12     0%
jesse/strategies/TestFuturesExchangeAvailableMargin/__init__.py                                               35     35     0%
jesse/strategies/TestHasEntryOrders/__init__.py                                                               17     17     0%
jesse/strategies/TestIncreasedAndReducedCount/__init__.py                                                     30     30     0%
jesse/strategies/TestInsufficientMargin1/__init__.py                                                          14     14     0%
jesse/strategies/TestInsufficientMargin2/__init__.py                                                          14     14     0%
jesse/strategies/TestInsufficientMargin3/__init__.py                                                          14     14     0%
jesse/strategies/TestLeverageProperty1/__init__.py                                                            14     14     0%
jesse/strategies/TestLeverageProperty2/__init__.py                                                            14     14     0%
jesse/strategies/TestLiquidationInCrossModeForShortTrade/__init__.py                                          23     23     0%
jesse/strategies/TestLiquidationInIsolatedModeForLongTrade/__init__.py                                        24     24     0%
jesse/strategies/TestLiquidationInIsolatedModeForShortTrade/__init__.py                                       24     24     0%
jesse/strategies/TestLogMethodInStrategyClass/__init__.py                                                     17     17     0%
jesse/strategies/TestMarkPrice/__init__.py                                                                    17     17     0%
jesse/strategies/TestMarketOrderForLowPriceDifference/__init__.py                                             18     18     0%
jesse/strategies/TestMetrics1/__init__.py                                                                     38     38     0%
jesse/strategies/TestMultipleEntryOrdersUpdateEntryLongPositions/__init__.py                                  35     35     0%
jesse/strategies/TestMultipleEntryOrdersUpdateEntryShortPositions/__init__.py                                 41     41     0%
jesse/strategies/TestPortfolioValue/__init__.py                                                               20     20     0%
jesse/strategies/TestPositionWithLeverage1/__init__.py                                                        17     17     0%
jesse/strategies/TestPositionWithLeverage2/__init__.py                                                        19     19     0%
jesse/strategies/TestPositions/__init__.py                                                                    15     15     0%
jesse/strategies/TestReduceOnlyMarketOrders/__init__.py                                                       18     18     0%
jesse/strategies/TestSpotNegativeBalance/__init__.py                                                          14     14     0%
jesse/strategies/TestStopLossPriceIsReplacedWithMarketOrderForBetterPriceLongPosition/__init__.py             20     20     0%
jesse/strategies/TestStopLossPriceIsReplacedWithMarketOrderForBetterPriceShortPosition/__init__.py            20     20     0%
jesse/strategies/TestTakeProfitPriceIsReplacedWithMarketOrderWhenMoreConvenientLongPosition/__init__.py       20     20     0%
jesse/strategies/TestTakeProfitPriceIsReplacedWithMarketOrderWhenMoreConvenientShortPosition/__init__.py      20     20     0%
jesse/strategies/TestWalletBalance/__init__.py                                                                34     34     0%
jesse/strategies/__init__.py                                                                                   1      0   100%
jesse/utils.py                                                                                               127     97    24%
jesse/version.py                                                                                               1      1     0%
setup.py                                                                                                       7      7     0%
tests/__init__.py                                                                                              0      0   100%
tests/data/__init__.py                                                                                         2      0   100%
tests/data/test_candles_0.py                                                                                   2      0   100%
tests/data/test_candles_1.py                                                                                   2      0   100%
tests/data/test_candles_indicators.py                                                                         19      0   100%
tests/test_backtest.py                                                                                        69     58    16%
tests/test_binance_inverse_futures.py                                                                          7      4    43%
tests/test_broker.py                                                                                         198    178    10%
tests/test_candle_service.py                                                                                  41     34    17%
tests/test_completed_trade.py                                                                                 42     28    33%
tests/test_conflicting_orders.py                                                                              43     29    33%
tests/test_exchange.py                                                                                        20     13    35%
tests/test_helpers.py                                                                                        317    239    25%
tests/test_import_candles.py                                                                                  47     37    21%
tests/test_indicators.py                                                                                    1523   1521     1%
tests/test_isolated_backtest.py                                                                               64     56    12%
tests/test_metrics.py                                                                                         39     33    15%
tests/test_order.py                                                                                           20     13    35%
tests/test_parent_strategy.py                                                                                536    462    14%
tests/test_position.py                                                                                       110     91    17%
tests/test_router.py                                                                                          14      9    36%
tests/test_state_candle.py                                                                                    75     64    15%
tests/test_state_exchanges.py                                                                                 15      9    40%
tests/test_state_logs.py                                                                                       5      1    80%
tests/test_state_orderbook.py                                                                                 41     33    20%
tests/test_state_orders.py                                                                                    43     33    23%
tests/test_state_ticker.py                                                                                    35     28    20%
tests/test_state_trades.py                                                                                    32     26    19%
tests/test_utils.py                                                                                          112     93    17%
tests/utils.py                                                                                                37     25    32%
------------------------------------------------------------------------------------------------------------------------------
TOTAL                                                                                                      14589  12763    13%

=========================== short test summary info ============================
ERROR tests/test_indicators.py - ValueError: numpy.ndarray size changed, may ...
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 4.26s ===============================
````

**Comment by cryptocoinserver** [comment]
Seems to be related to this: [https://github.com/mrjbq7/ta-lib/issues/378](https://github.com/mrjbq7/ta-lib/issues/378)

**Comment by cryptocoinserver** [comment]
Updated the requirements. Should be fixed now.

**Comment by mahiso** [comment]
Thanks.

Rebuilt and test runs without error, but two warnings (unsure whether this is related):
```
=============================== warnings summary ===============================
tests/test_indicators.py::test_macdext
  /jesse-docker/jesse/indicators/nma.py:40: RuntimeWarning: invalid value encountered in log
    ln = np.log(source) * 1000

tests/test_indicators.py::test_macdext
  /jesse-docker/jesse/indicators/maaq.py:42: RuntimeWarning: invalid value encountered in true_divide
    ratio = np.where(noise == 0, 0, signal / noise)

```

Backtest runs fine now.

**Comment by cryptocoinserver** [comment]
Perfect. Will close this then. 
About the warnings. I think we can ignore them. They tell us that division by zero or in case of log the log of zero might happen.

**Comment by mrjbq7** [comment]
@cryptocoinserver what caused your numpy size changed issue?  i don't specify a version of numpy required in ta-lib?

**Comment by cryptocoinserver** [comment]
Numpy and ta-lib were pinned to an older version. Updated both to the most recent version. Error gone 🎉
