### ISSUE TITLE
jesse.exceptions.OrderNotAllowed: Cannot submit a reduce_position order when there is not open position

### ISSUE THREAD

**Issue by firesurf** [jesse-ai/jesse#32]
```
==== ETHUSD | 2020-02-05T12:00 | 197.63 | 197.51 | 198.4 | 195.82 | 18236.37
[2020-02-05T15:00:00+00:00]: balance changed from 12078.14018141486 to -24.872733937947487
[2020-02-05T15:00:00+00:00]: SUBMITTED order: ETHUSD, STOP, buy, 60.87, $198.44
[2020-02-05T15:49:00+00:00]: EXECUTED order: ETHUSD, STOP, buy, 60.87, $198.44
[2020-02-05T15:49:00+00:00]: OPENED long position: Bitfinex, ETHUSD, 60.87, $198.44
[2020-02-05T15:49:00+00:00]: Detected open position
[2020-02-05T15:49:00+00:00]: SUBMITTED order: ETHUSD, LIMIT, sell, -30.43, $229.33
[2020-02-05T15:49:00+00:00]: SUBMITTED order: ETHUSD, STOP, sell, -60.87, $191.33
==== ETHUSD | 2020-02-05T15:00 | 197.517 | 201.22 | 201.47 | 197.06 | 23105.77
==== BTCUSD | 2020-02-05T12:00 | 9418.0 | 9571.43 | 9583.8 | 9418.0 | 3145.39
==== ETHUSD | 2020-02-05T18:00 | 201.295 | 203.37 | 204.64 | 201.258 | 17941.14
==== ETHUSD | 2020-02-05T21:00 | 203.46 | 203.79 | 207.99 | 202.91 | 16343.85
==== BTCUSD | 2020-02-05T18:00 | 9571.4 | 9612.0 | 9731.9 | 9571.4 | 5429.39
==== ETHUSD | 2020-02-06T00:00 | 203.78 | 203.152 | 205.11 | 201.02 | 8212.96
==== ETHUSD | 2020-02-06T03:00 | 203.16 | 207.08 | 207.1 | 203.13 | 11347.61
==== BTCUSD | 2020-02-06T00:00 | 9612.1 | 9651.1 | 9661.2 | 9547.0 | 1236.78
[2020-02-06T06:00:00+00:00]: balance changed from -24.872733937947487 to -24.872733937947487
[2020-02-06T06:00:00+00:00]: SUBMITTED order: BTCUSD, STOP, buy, 0.0, $9695.77
[2020-02-06T07:56:00+00:00]: EXECUTED order: BTCUSD, STOP, buy, 0.0, $9695.77
[2020-02-06T07:56:00+00:00]: OPENED close position: Bitfinex, BTCUSD, 0.0, $9695.77
[2020-02-06T07:56:00+00:00]: Detected open position
Traceback (most recent call last):
  File "C:\Users\Markus\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Users\Markus\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Markus\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:/home/src/jesse/jesse/__init__.py", line 293, in backtest
    backtest_mode.run(start_date, finish_date, chart=chart, tradingview=tradingview)
  File "C:\home\src\jesse\jesse\modes\backtest_mode\__init__.py", line 58, in run
    simulator(candles)
  File "C:\home\src\jesse\jesse\modes\backtest_mode\__init__.py", line 193, in simulator
    _simulate_price_change_effect(short_candle, exchange, symbol)
  File "C:\home\src\jesse\jesse\modes\backtest_mode\__init__.py", line 298, in _simulate_price_change_effect
    order.execute()
  File "C:\home\src\jesse\jesse\models\Order.py", line 153, in execute
    p._on_executed_order(self)
  File "C:\home\src\jesse\jesse\models\Position.py", line 302, in _on_executed_order
    self.strategy._on_updated_position(order)
  File "C:\home\src\jesse\jesse\strategies\Strategy.py", line 133, in _on_updated_position
    self._on_open_position()
  File "C:\home\src\jesse\jesse\strategies\Strategy.py", line 683, in _on_open_position
    self.broker.reduce_position_at(
  File "C:\home\src\jesse\jesse\services\broker.py", line 91, in reduce_position_at
    raise OrderNotAllowed(
jesse.exceptions.OrderNotAllowed: Cannot submit a reduce_position order when there is not open position
```

I think the problem is here:
`[2020-02-06T06:00:00+00:00]: SUBMITTED order: BTCUSD, STOP, buy, 0.0, $9695.77
[2020-02-06T07:56:00+00:00]: EXECUTED order: BTCUSD, STOP, buy, 0.0, $9695.77
[2020-02-06T07:56:00+00:00]: OPENED close position: Bitfinex, BTCUSD, 0.0, $9695.77`
QTY is 0.0

The backtest has two routes. One for BTCUSD and one for ETHUSD. Both with the same strategy.
If i backtest the strategy alone it works.

**Comment by firesurf** [comment]
I think i found it. The strategies conflicted over the capital
I added self.capital/2 in the strategy. Now the backtest works.
Do we check for a qty == 0?

**Comment by saleh-mir** [comment]
> Do we check for a qty == 0?

I don't think so

**Comment by saleh-mir** [comment]
I just added validation for `qty == 0`
