### ISSUE TITLE
Bug in handle_queued_orders() for jesse_live

### ISSUE THREAD

**Issue by ynzheng** [jesse-ai/jesse#354]
with multi routes for jesse_live 0.37.0,I got so many ERROR msg in logs like:

[ERROR | 2022-06-16T16:00:08] Traceback (most recent call last):
  File "jesse_live/exchanges/BinancePerpetualFutures.py", line 518, in jesse_live.exchanges.BinancePerpetualFutures.BinancePerpetualFutures.submit_order
KeyError: 'orderId'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "jesse_live/exchanges/LiveExchange.py", line 307, in jesse_live.exchanges.LiveExchange.LiveExchange._connect_ws._on_message
  File "jesse_live/exchanges/BinancePerpetualFutures.py", line 363, in jesse_live.exchanges.BinancePerpetualFutures.BinancePerpetualFutures.on_ws_message
  File "jesse_live/exchanges/BinancePerpetualFutures.py", line 458, in jesse_live.exchanges.BinancePerpetualFutures.BinancePerpetualFutures.prepare_candle_stream
  File "jesse_live/exchanges/LiveExchange.py", line 924, in jesse_live.exchanges.LiveExchange.LiveExchange.add_candle
  File "jesse_live/exchanges/LiveExchange.py", line 937, in jesse_live.exchanges.LiveExchange.LiveExchange.handle_queued_orders
  File "jesse_live/exchanges/BinancePerpetualFutures.py", line 520, in jesse_live.exchanges.BinancePerpetualFutures.BinancePerpetualFutures.submit_order
jesse.exceptions.ExchangeRejectedOrder: [400 error]: b'{"code":-2022,"msg":"ReduceOnly Order is rejected."}'

after long time research, I think I got why this is happend.

in function of handle_queued_orders() for jesse_live,

the bug is in "def handle_queued_orders(self, arr)"

I think it should be  "def handle_queued_orders(self, arr, symbol)"

without the last symbol parameter , it will run ETH-USDT check in BTC-USDT loop...or etc

so it should be like "if order_symbol == symbol"... then in the BTC-USDT loop,it will check only BTC-USDT,not other routes

JUST FYI

**Comment by saleh-mir** [comment]
I took a look at my code. I think that's exactly it. I'll test it and push a fix soon. Thanks for letting me know!

**Comment by saleh-mir** [comment]
I just pushed version `0.37.1` which improves this if not completely fix. I say that because even though now the symbol checking is in place, and so is the normal handling of rejected orders, I'm not sure about the reason for your orders getting rejected in the first place. I looked at your logs too (that you sent via the report). Nothing seemed wrong. 

Please update and let me know if it happened again (especially via reports so I can see the logs again)
