### ISSUE TITLE
TypeError: Cannot parse single argument of type .

### ISSUE THREAD

**Issue by shhhmel** [jesse-ai/jesse#360]
**Describe the bug**
After update to 0.39.2 if I use Extra Routes it fails with error.

```
Traceback (most recent call last):
  File "/jesse-docker/jesse/services/multiprocessing.py", line 20, in run
    mp.Process.run(self)
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/jesse-docker/jesse/modes/backtest_mode.py", line 82, in run
    candles = load_candles(start_date, finish_date)
  File "/jesse-docker/jesse/modes/backtest_mode.py", line 177, in load_candles
    required_candles.inject_required_candles_to_store(
  File "/jesse-docker/jesse/services/required_candles.py", line 112, in inject_required_candles_to_store
    store.candles.batch_add_candle(candles, exchange, symbol, '1m', with_generation=False)
  File "/jesse-docker/jesse/store/state_candles.py", line 327, in batch_add_candle
    self.add_candle(c, exchange, symbol, timeframe, with_execution=False, with_generation=with_generation, with_skip=False)
  File "/jesse-docker/jesse/store/state_candles.py", line 187, in add_candle
    f"Could not find the candle with timestamp {jh.timestamp_to_time(candle[0])} in the storage. Last candle's timestamp: {jh.timestamp_to_time(arr[-1])}. timeframe: {timeframe}, exchange: {exchange}, symbol: {symbol}"
  File "/jesse-docker/jesse/helpers.py", line 776, in timestamp_to_time
    return str(arrow.get(timestamp / 1000))
  File "/usr/local/lib/python3.9/site-packages/arrow/api.py", line 91, in get
    return _factory.get(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/arrow/factory.py", line 267, in get
    raise TypeError(f"Cannot parse single argument of type {type(arg)!r}.")
TypeError: Cannot parse single argument of type .
```

**To Reproduce**
You can test on this strategy https://github.com/jesse-ai/example-strategies/blob/master/DUAL_THRUST/__init__.py

**Expected behavior**

**Screenshots**

**Enviroment (please complete the following information):**
 - OS:  Ubuntu
 - Python: 3.9
 - Version 0.39.2

**Comment by saleh-mir** [comment]
Just pushed `0.39.3` to fix this. Thank you for reporting it
