### ISSUE TITLE
jesse\services\installer.py", line 92, in install     subprocess.check_call(['rm', filepath])

### ISSUE THREAD

**Issue by qwpto** [jesse-ai/jesse#361]
**Describe the bug**
live plugin fails during installation with:
>jesse install-live
is_64_bit True
is_arm False
Downloading the latest version of the live-trade plugin...
Installing jesse_live-0.39.0-cp39-cp39-win_amd64.whl...
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Processing c:\users\xxxxc\onedrive\documents\github\jb1local\storage\jesse_live-0.39.0-cp39-cp39-win_amd64.whl
Requirement already satisfied: starkbank-ecdsa in c:\users\xxxxc\appdata\local\programs\python\python39\lib\site-packages (from jesse-live==0.39.0) (2.0.3)
Installing collected packages: jesse-live
Successfully installed jesse-live-0.39.0
Traceback (most recent call last):
  File "C:\Users\xxxxc\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\xxxxc\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\xxxxc\AppData\Local\Programs\Python\Python39\Scripts\jesse.exe\__main__.py", line 7, in <module>
  File "C:\Users\xxxxc\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\xxxxc\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\xxxxc\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\xxxxc\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\xxxxc\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\xxxxc\AppData\Local\Programs\Python\Python39\lib\site-packages\jesse\__init__.py", line 195, in install_live
    install(HAS_LIVE_TRADE_PLUGIN, strict)
  File "C:\Users\xxxxc\AppData\Local\Programs\Python\Python39\lib\site-packages\jesse\services\installer.py", line 92, in install
    subprocess.check_call(['rm', filepath])
  File "C:\Users\xxxxc\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 368, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\xxxxc\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\xxxxc\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\xxxxc\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**To Reproduce**
0.39.4:
>jesse install-live

**Expected behavior**
Successfully installed jesse-live-0.39.0

**Screenshots**
na

**Enviroment (please complete the following information):**
 - OS:windows

**Additional context**
https://discordapp.com/channels/771690508413829141/834865870806581299/1013002918116470844

**Comment by saleh-mir** [comment]
This is already going on Discord
