### ISSUE TITLE
Error on Jesse update

### ISSUE THREAD

**Issue by shhhmel** [jesse-ai/jesse#366]
**Describe the bug**
If I run `pip install -U jesse` or `jesse install-live`
I have error.

```
Requirement already satisfied: jesse in /usr/local/lib/python3.8/dist-packages (0.39.3)
Collecting jesse
  Downloading jesse-0.39.5-py3-none-any.whl (1.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 20.1 MB/s eta 0:00:00
Requirement already satisfied: python-dotenv==0.19.2 in /usr/local/lib/python3.8/dist-packages (from jesse) (0.19.2)
Requirement already satisfied: arrow==1.2.1 in /usr/local/lib/python3.8/dist-packages (from jesse) (1.2.1)
Requirement already satisfied: pytest==6.2.5 in /usr/local/lib/python3.8/dist-packages (from jesse) (6.2.5)
Requirement already satisfied: redis==4.1.4 in /usr/local/lib/python3.8/dist-packages (from jesse) (4.1.4)
Requirement already satisfied: websocket-client==1.2.3 in /usr/local/lib/python3.8/dist-packages (from jesse) (1.2.3)
Requirement already satisfied: pydash==5.1.0 in /usr/local/lib/python3.8/dist-packages (from jesse) (5.1.0)
Requirement already satisfied: timeloop==1.0.2 in /usr/local/lib/python3.8/dist-packages (from jesse) (1.0.2)
Requirement already satisfied: simplejson==3.16.0 in /usr/local/lib/python3.8/dist-packages (from jesse) (3.16.0)
Requirement already satisfied: fastapi==0.74.0 in /usr/local/lib/python3.8/dist-packages (from jesse) (0.74.0)
Requirement already satisfied: PyWavelets==1.2.0 in /usr/local/lib/python3.8/dist-packages (from jesse) (1.2.0)
Requirement already satisfied: aioredis==1.3.1 in /usr/local/lib/python3.8/dist-packages (from jesse) (1.3.1)
Requirement already satisfied: numpy-groupies==0.9.14 in /usr/local/lib/python3.8/dist-packages (from jesse) (0.9.14)
Requirement already satisfied: aiofiles==0.7.0 in /usr/local/lib/python3.8/dist-packages (from jesse) (0.7.0)
Requirement already satisfied: newtulipy==0.4.6 in /usr/local/lib/python3.8/dist-packages (from jesse) (0.4.6)
Requirement already satisfied: quantstats==0.0.47 in /usr/local/lib/python3.8/dist-packages (from jesse) (0.0.47)
Requirement already satisfied: TA-Lib==0.4.24 in /usr/local/lib/python3.8/dist-packages (from jesse) (0.4.24)
Requirement already satisfied: blinker==1.4 in /usr/local/lib/python3.8/dist-packages (from jesse) (1.4)
Requirement already satisfied: pandas==1.4.0 in /usr/local/lib/python3.8/dist-packages (from jesse) (1.4.0)
Requirement already satisfied: scipy==1.8.0 in /usr/local/lib/python3.8/dist-packages (from jesse) (1.8.0)
Requirement already satisfied: click==8.0.3 in /usr/local/lib/python3.8/dist-packages (from jesse) (8.0.3)
Requirement already satisfied: numpy==1.23.0 in /usr/local/lib/python3.8/dist-packages (from jesse) (1.23.0)
Requirement already satisfied: requests==2.26.0 in /usr/local/lib/python3.8/dist-packages (from jesse) (2.26.0)
Requirement already satisfied: statsmodels==0.13.2 in /usr/local/lib/python3.8/dist-packages (from jesse) (0.13.2)
Requirement already satisfied: peewee==3.14.8 in /usr/local/lib/python3.8/dist-packages (from jesse) (3.14.8)
Requirement already satisfied: tabulate==0.8.9 in /usr/local/lib/python3.8/dist-packages (from jesse) (0.8.9)
Requirement already satisfied: websockets==9.1.0 in /usr/local/lib/python3.8/dist-packages (from jesse) (9.1)
Requirement already satisfied: uvicorn==0.14.0 in /usr/local/lib/python3.8/dist-packages (from jesse) (0.14.0)
Requirement already satisfied: matplotlib==3.5.1 in /usr/local/lib/python3.8/dist-packages (from jesse) (3.5.1)
Requirement already satisfied: mplfinance==0.12.8b6 in /usr/local/lib/python3.8/dist-packages (from jesse) (0.12.8b6)
Requirement already satisfied: psycopg2-binary==2.9.2 in /usr/local/lib/python3.8/dist-packages (from jesse) (2.9.2)
Requirement already satisfied: async-timeout in /usr/local/lib/python3.8/dist-packages (from aioredis==1.3.1->jesse) (4.0.2)
Requirement already satisfied: hiredis in /usr/local/lib/python3.8/dist-packages (from aioredis==1.3.1->jesse) (2.0.0)
Requirement already satisfied: python-dateutil>=2.7.0 in /usr/local/lib/python3.8/dist-packages (from arrow==1.2.1->jesse) (2.8.2)
Requirement already satisfied: starlette==0.17.1 in /usr/local/lib/python3.8/dist-packages (from fastapi==0.74.0->jesse) (0.17.1)
Requirement already satisfied: pydantic!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0,>=1.6.2 in /usr/local/lib/python3.8/dist-packages (from fastapi==0.74.0->jesse) (1.9.1)
Requirement already satisfied: pyparsing>=2.2.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib==3.5.1->jesse) (3.0.7)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.8/dist-packages (from matplotlib==3.5.1->jesse) (4.31.2)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.8/dist-packages (from matplotlib==3.5.1->jesse) (9.0.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.8/dist-packages (from matplotlib==3.5.1->jesse) (21.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib==3.5.1->jesse) (1.4.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.8/dist-packages (from matplotlib==3.5.1->jesse) (0.11.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas==1.4.0->jesse) (2022.1)
Requirement already satisfied: iniconfig in /usr/local/lib/python3.8/dist-packages (from pytest==6.2.5->jesse) (1.1.1)
Requirement already satisfied: toml in /usr/local/lib/python3.8/dist-packages (from pytest==6.2.5->jesse) (0.10.2)
Requirement already satisfied: pluggy<2.0,>=0.12 in /usr/local/lib/python3.8/dist-packages (from pytest==6.2.5->jesse) (1.0.0)
Requirement already satisfied: attrs>=19.2.0 in /usr/local/lib/python3.8/dist-packages (from pytest==6.2.5->jesse) (21.4.0)
Requirement already satisfied: py>=1.8.2 in /usr/local/lib/python3.8/dist-packages (from pytest==6.2.5->jesse) (1.11.0)
Requirement already satisfied: seaborn>=0.9.0 in /usr/local/lib/python3.8/dist-packages (from quantstats==0.0.47->jesse) (0.11.2)
Requirement already satisfied: yfinance>=0.1.63 in /usr/local/lib/python3.8/dist-packages (from quantstats==0.0.47->jesse) (0.1.72)
Requirement already satisfied: deprecated>=1.2.3 in /usr/local/lib/python3.8/dist-packages (from redis==4.1.4->jesse) (1.2.13)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests==2.26.0->jesse) (2019.11.28)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests==2.26.0->jesse) (2.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests==2.26.0->jesse) (1.25.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.8/dist-packages (from requests==2.26.0->jesse) (2.0.12)
Requirement already satisfied: patsy>=0.5.2 in /usr/local/lib/python3.8/dist-packages (from statsmodels==0.13.2->jesse) (0.5.2)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.8/dist-packages (from uvicorn==0.14.0->jesse) (0.13.0)
Requirement already satisfied: asgiref>=3.3.4 in /usr/local/lib/python3.8/dist-packages (from uvicorn==0.14.0->jesse) (3.5.2)
Requirement already satisfied: anyio<4,>=3.0.0 in /usr/local/lib/python3.8/dist-packages (from starlette==0.17.1->fastapi==0.74.0->jesse) (3.6.1)
Requirement already satisfied: wrapt<2,>=1.10 in /usr/local/lib/python3.8/dist-packages (from deprecated>=1.2.3->redis==4.1.4->jesse) (1.14.1)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from patsy>=0.5.2->statsmodels==0.13.2->jesse) (1.14.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.8/dist-packages (from pydantic!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0,>=1.6.2->fastapi==0.74.0->jesse) (4.2.0)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.8/dist-packages (from yfinance>=0.1.63->quantstats==0.0.47->jesse) (0.0.11)
Requirement already satisfied: lxml>=4.5.1 in /usr/local/lib/python3.8/dist-packages (from yfinance>=0.1.63->quantstats==0.0.47->jesse) (4.9.1)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.8/dist-packages (from anyio<4,>=3.0.0->starlette==0.17.1->fastapi==0.74.0->jesse) (1.2.0)
Installing collected packages: jesse
  Attempting uninstall: jesse
    Found existing installation: jesse 0.39.3
    Uninstalling jesse-0.39.3:
      Successfully uninstalled jesse-0.39.3
Successfully installed jesse-0.39.5
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/logging.py", line 177, in emit
    self.console.print(renderable, overflow="ignore", crop=False, style=style)
  File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/console.py", line 1752, in print
    extend(render(renderable, render_options))
  File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/console.py", line 1390, in render
    for render_output in iter_render:
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/logging.py", line 134, in __rich_console__
    for line in lines:
  File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/segment.py", line 245, in split_lines
    for segment in segments:
  File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/console.py", line 1368, in render
    renderable = rich_cast(renderable)
  File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/protocol.py", line 36, in rich_cast
    renderable = cast_method()
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/self_outdated_check.py", line 130, in __rich__
    pip_cmd = get_best_invocation_for_this_pip()
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/entrypoints.py", line 58, in get_best_invocation_for_this_pip
    if found_executable and os.path.samefile(
  File "/usr/lib/python3.8/genericpath.py", line 101, in samefile
    s2 = os.stat(f2)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/pip3.8'
Call stack:
  File "/usr/local/bin/pip", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/main.py", line 70, in main
    return command.main(cmd_args)
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/base_command.py", line 101, in main
    return self._main(args)
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/base_command.py", line 223, in _main
    self.handle_pip_version_check(options)
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/req_command.py", line 148, in handle_pip_version_check
    pip_self_version_check(session, options)
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/self_outdated_check.py", line 237, in pip_self_version_check
    logger.info("[present-rich] %s", upgrade_prompt)
  File "/usr/lib/python3.8/logging/__init__.py", line 1446, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 954, in handle
    self.emit(record)
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/logging.py", line 179, in emit
    self.handleError(record)
Message: '[present-rich] %s'
Arguments: (UpgradePrompt(old='22.1.2', new='22.2.2'),)
```

**Enviroment (please complete the following information):**
 - OS: Ubuntu
 - Version 0.39.3

**Additional context**
```
pip --version
pip 22.1.2 from /usr/local/lib/python3.8/dist-packages/pip (python 3.8)
```

```
python --version
zsh: command not found: python
```

```
python3 --version
Python 3.8.10
```

**Comment by saleh-mir** [comment]
Seems like it did install tho:
```
Successfully installed jesse-0.39.5
```

Run `pip show jesse` to see which version it reports.

**Comment by saleh-mir** [comment]
This doesn't seem like a bug. Seems like a Python package handling issue. You'll get better help asking this on Discord:
https://jesse.trade/discord
