### ISSUE TITLE
install error For countries that do not meet the network conditions

### ISSUE THREAD

**Issue by zhihuba** [jesse-ai/jesse#377]
# install error
## installation steps
- ubuntu20.04
- conda create -n jesse38 python=3.8
- pip install jesse
So far everything is fine
```bash
git clone https://github.com/jesse-ai/project-template jesse-bot
cd jesse-bot
mv .env.example .env
vim .env
```
## run
* jesse run
## Error details
```python
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/jesse38/bin/jesse", line 5, in <module>
    from jesse.__init__ import cli
  File "/home/ubuntu/miniconda3/envs/jesse38/lib/python3.8/site-packages/jesse/__init__.py", line 12, in <module>
    from jesse.services import auth as authenticator
  File "/home/ubuntu/miniconda3/envs/jesse38/lib/python3.8/site-packages/jesse/services/auth.py", line 5, in <module>
    from jesse.services.env import ENV_VALUES
  File "/home/ubuntu/miniconda3/envs/jesse38/lib/python3.8/site-packages/jesse/services/env.py", line 18, in <module>
    if jh.is_unit_testing():
  File "/home/ubuntu/miniconda3/envs/jesse38/lib/python3.8/site-packages/jesse/helpers.py", line 368, in is_unit_testing
    from jesse.config import config
  File "/home/ubuntu/miniconda3/envs/jesse38/lib/python3.8/site-packages/jesse/config.py", line 2, in <module>
    from jesse.modes.utils import get_exchange_type
  File "/home/ubuntu/miniconda3/envs/jesse38/lib/python3.8/site-packages/jesse/modes/utils.py", line 2, in <module>
    from jesse.services import logger
  File "/home/ubuntu/miniconda3/envs/jesse38/lib/python3.8/site-packages/jesse/services/logger.py", line 3, in <module>
    from jesse.services.redis import sync_publish
  File "/home/ubuntu/miniconda3/envs/jesse38/lib/python3.8/site-packages/jesse/services/redis.py", line 23, in <module>
    async_redis = asyncio.run(init_redis())
  File "/home/ubuntu/miniconda3/envs/jesse38/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/ubuntu/miniconda3/envs/jesse38/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/ubuntu/miniconda3/envs/jesse38/lib/python3.8/site-packages/jesse/services/redis.py", line 12, in init_redis
    return await aioredis.create_redis_pool(
  File "/home/ubuntu/miniconda3/envs/jesse38/lib/python3.8/site-packages/aioredis/commands/__init__.py", line 188, in create_redis_pool
    pool = await create_pool(address, db=db,
  File "/home/ubuntu/miniconda3/envs/jesse38/lib/python3.8/site-packages/aioredis/pool.py", line 58, in create_pool
    await pool._fill_free(override_min=False)
  File "/home/ubuntu/miniconda3/envs/jesse38/lib/python3.8/site-packages/aioredis/pool.py", line 383, in _fill_free
    conn = await self._create_new_connection(self._address)
  File "/home/ubuntu/miniconda3/envs/jesse38/lib/python3.8/site-packages/aioredis/connection.py", line 111, in create_connection
    reader, writer = await asyncio.wait_for(open_connection(
  File "/home/ubuntu/miniconda3/envs/jesse38/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/home/ubuntu/miniconda3/envs/jesse38/lib/python3.8/site-packages/aioredis/stream.py", line 23, in open_connection
    transport, _ = await get_event_loop().create_connection(
  File "/home/ubuntu/miniconda3/envs/jesse38/lib/python3.8/asyncio/base_events.py", line 986, in create_connection
    infos = await self._ensure_resolved(
  File "/home/ubuntu/miniconda3/envs/jesse38/lib/python3.8/asyncio/base_events.py", line 1365, in _ensure_resolved
    return await loop.getaddrinfo(host, port, family=family, type=type,
  File "/home/ubuntu/miniconda3/envs/jesse38/lib/python3.8/asyncio/base_events.py", line 825, in getaddrinfo
    return await self.run_in_executor(
  File "/home/ubuntu/miniconda3/envs/jesse38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ubuntu/miniconda3/envs/jesse38/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
```
Trying to install with docker still persists error
> When .env doesn't exist everything works fine
> from jesse import research
What did i do wrong? Guess it's a network issue. Is it possible to print the detailed log of the link

**Comment by saleh-mir** [comment]
Please read:
https://jesse.trade/help/faq/how-to-solve-the-socketgaierror-errno-3-temporary-failure-in-name-resolution-error-when-starting-jesse

Please use Discord for support
