### ISSUE TITLE
[Live Mode] Session terminated as the result of an uncaught exception

### ISSUE THREAD

**Issue by shhhmel** [jesse-ai/jesse#378]
**Describe the bug**
Bug occured on Live Mode Session. No notification in Telegram.
Log:

```
[INFO | 2022-11-05T11:40:16] Authenticated to Binance Perpetual Futures successfully.
[INFO | 2022-11-05T11:55:13] Error fetching candles via REST for ETH-USDT from Binance Perpetual Futures. No worries, will try later. Error: "('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
[INFO | 2022-11-05T11:55:16] ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
[ERROR | 2022-11-05T11:55:16] ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
[INFO | 2022-11-05T11:55:16] Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/dist-packages/timeloop/job.py", line 19, in run
    self.execute(*self.args, **self.kwargs)
  File "jesse_live/exchanges/Binance/BinancePerpetualFuturesMain.py", line 41, in jesse_live.exchanges.Binance.BinancePerpetualFuturesMain.BinancePerpetualFuturesMain.__init__.t1_function
  File "jesse_live/exchanges/Binance/BinancePerpetualFuturesMain.py", line 120, in jesse_live.exchanges.Binance.BinancePerpetualFuturesMain.BinancePerpetualFuturesMain._authenticate
  File "jesse_live/exchanges/Binance/BinancePerpetualFuturesMain.py", line 106, in jesse_live.exchanges.Binance.BinancePerpetualFuturesMain.BinancePerpetualFuturesMain._authenticate
  File "jesse_live/exchanges/Binance/BinancePerpetualFuturesMain.py", line 76, in jesse_live.exchanges.Binance.BinancePerpetualFuturesMain.BinancePerpetualFuturesMain.submit_request
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

[INFO | 2022-11-05T11:55:16] Session terminated as the result of an uncaught exception
[ERROR | 2022-11-05T11:55:16] Session terminated as the result of an uncaught exception
```

**Expected behavior**
At least notify via Telegram.

**Enviroment (please complete the following information):**
 - OS: Ubuntu
 - Version: Jesse - 0.40.4, Live plugin - 0.40.3

**Comment by saleh-mir** [comment]
If the error is unexpected, it crashes so the telegram notifications don't work either. However, if you don't see regular position notifications, that's a sign to check on the running bot. 

I can debug further if you can report this via the GUI and send me raw exchange logs as well.

**Comment by shhhmel** [comment]
@saleh-mir I am not able to report via GUI because Live session finishes after crash and I can't see Report button anymore (
How can I send raw exchange logs?
