### ISSUE TITLE
Live-trading plugin cannot be run on ARM platform

### ISSUE THREAD

**Issue by petrmac** [jesse-ai/jesse#389]
Upon starting the docker on ARM and attempting to download the live-trading plugin, I get the following error:

```
is_64_bit True                                                                                                                                                            │
│ is_arm False                                                                                                                                                              │
│ Downloading the latest version of the live-trade plugin...                                                                                                                │
│ Installing jesse_live-0.41.4-cp39-cp39-manylinux2010_x86_64.whl...                                                                                                        │
│ ERROR: jesse_live-0.41.4-cp39-cp39-manylinux2010_x86_64.whl is not a supported wheel on this platform.                                                                    │
│ Traceback (most recent call last):                                                                                                                                        │
│   File "/usr/local/bin/jesse", line 33, in <module>                                                                                                                       │
│     sys.exit(load_entry_point('jesse', 'console_scripts', 'jesse')())                                                                                                     │
│   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__                                                                                     │
│     return self.main(*args, **kwargs)                                                                                                                                     │
│   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main                                                                                         │
│     rv = self.invoke(ctx)                                                                                                                                                 │
│   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke                                                                                       │
│     return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                                                               │
│   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke                                                                                       │
│     return ctx.invoke(self.callback, **ctx.params)                                                                                                                        │
│   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke                                                                                        │
│     return __callback(*args, **kwargs)                                                                                                                                    │
│   File "/jesse-docker/jesse/__init__.py", line 195, in install_live                                                                                                       │
│     install(HAS_LIVE_TRADE_PLUGIN, strict)                                                                                                                                │
│   File "/jesse-docker/jesse/services/installer.py", line 89, in install                                                                                                   │
│     _pip_install(filepath)                                                                                                                                                │
│   File "/jesse-docker/jesse/services/installer.py", line 11, in _pip_install                                                                                              │
│     subprocess.check_call([sys.executable, "-m", "pip", "install", package])                                                                                              │
│   File "/usr/local/lib/python3.9/subprocess.py", line 373, in check_call                                                                                                  │
│     raise CalledProcessError(retcode, cmd)                                                                                                                                │
│ subprocess.CalledProcessError: Command '['/usr/local/bin/python', '-m', 'pip', 'install', 'storage/jesse_live-0.41.4-cp39-cp39-manylinux2010_x86_64.whl']' returned non-z │
│ Stream closed EOF for jesse/jesse-78bb7856d8-84q77 (jesse)
```

Could the ARM be supported as well, please? 
Happy to help with the efforts.

**Comment by edu-diaz** [comment]
@saleh-mir I am trying to run this in my k3s raspi cluster and I have the same problem, I think supporting linux arm would be great
