### ISSUE TITLE
Optimize wont work on Windows: EOFError: Ran out of input

### ISSUE THREAD

**Issue by itsaLca** [jesse-ai/jesse#70]
hey, when i run: 

- jesse optimize '2020-01-01' '2020-09-28' 10

im running into this trouble on jesse version 0.12.2

```
============================== EXCEPTION TRACEBACK:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Projects\Environments\jesse\Scripts\jesse.exe\__main__.py", line 7, in <module>
    sys.exit(cli())
  File "c:\projects\environments\jesse\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\projects\environments\jesse\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\projects\environments\jesse\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\projects\environments\jesse\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\projects\environments\jesse\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\projects\environments\jesse\lib\site-packages\jesse\__init__.py", line 352, in optimize
    optimize_mode(start_date, finish_date, optimal_total, cpu)
  File "c:\projects\environments\jesse\lib\site-packages\jesse\modes\optimize_mode\__init__.py", line 172, in optimize_mode
    optimizer.run()
  File "c:\projects\environments\jesse\lib\site-packages\jesse\modes\optimize_mode\Genetics.py", line 382, in run
    return self.evolve()
  File "c:\projects\environments\jesse\lib\site-packages\jesse\modes\optimize_mode\Genetics.py", line 218, in evolve
    self.generate_initial_population()
  File "c:\projects\environments\jesse\lib\site-packages\jesse\modes\optimize_mode\Genetics.py", line 100, in generate_initial_population
    w.start()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
=========================================================================

 Uncaught Exception: AttributeError: Can't pickle local object 'Genetics.generate_initial_population.<locals>.get_fitness'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

```

Any idea(s)?

**Comment by firesurf** [comment]
https://stackoverflow.com/questions/8804830/python-multiprocessing-picklingerror-cant-pickle-type-function
Seems to be multiprocessing related. Didn't have this error yet. Seems a Windows thing?

**Comment by itsaLca** [comment]
Indeed, under a fresh ubuntu 18.04 it's doing its job.

**Comment by saleh-mir** [comment]
This issue is most likely solved in the upcoming dashboard release. Because I rewrote the our multiprocessing code in it
